version: "3.9"

services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      AUTH_CHANNEL: $AUTH_CHANNEL  # defaults to None
      TG_BOT_TOKEN: $TG_BOT_TOKEN  # defaults to None
      OWNER_ID: $OWNER_ID #default
      SUDO_USERS: $SUDO_USERS
      CAP_STYLE: $CAP_STYLE
      UPTOBOX_TOKEN: $UPTOBOX_TOKEN
      EMAIL: $EMAIL
      PWSSD: $PWSSD
      GDRIVE_FOLDER_ID: $GDRIVE_FOLDER_ID
      CRYPT: $CRYPT
      PHPSESSID: $PHPSESSID
      HUB_CRYPT: $HUB_CRYPT
      IMDB_TEMPLATE: $IMDB_TEMPLATE
